sudo: true
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
  - '5'
  - '4'
  - iojs-v3
  - iojs-v2
  - iojs-v1
  - '0.12'
  - '0.11.15'
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - |
      if [ "$BUILD_LEADER" = "YES" -a "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
        echo "Checking coverage and release status."
        npm run semantic-release
      else
        echo "Either I'm a minion or the build failed. No semantic-releasing for me."
      fi
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
