sudo: true
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
